### ISSUE TITLE
Delete Category

### ISSUE THREAD

**Issue by tthuyhuong** [Pick-and-buy/UGTS-Back-stage#63]
Khi xóa danh một mục không tồn tại ->
danh mục không tồn tại vẫn được xóa thành công.

input data: category name( không tồn tại): Handba

![Screenshot 2024-07-05 025848](https://github.com/Pick-and-buy/UGTS-Back-stage/assets/161487881/d606778f-f06a-4ab8-abe2-e31040f917f6)

**Comment by Tran-Anh-Quang** [comment]
refactor code và đã handle issue
![image](https://github.com/user-attachments/assets/2dd718f1-fe0e-4c6c-b419-02eb5df57827)
