### ISSUE TITLE
(Order)Get Order by order id 

### ISSUE THREAD

**Issue by tthuyhuong** [Pick-and-buy/UGTS-Back-stage#77]
input :452c0e71-81cd-4539-927a-fa723e28eb74 -> trả về tất cả các order 
input: orderId invalid :452c0e71-81cd-4539 -> trả về tất cả các order
![image](https://github.com/user-attachments/assets/455d1975-a968-4108-b9e0-32a382a7d758)

**Comment by thanhlam1211** [comment]
Hường cap thêm phần order ở dưới đi, xem phần order trả về bao nhiêu cái

**Comment by tthuyhuong** [comment]
![Screenshot 2024-07-18 151146](https://github.com/user-attachments/assets/361b0ced-de20-4787-95f3-628f3338b65a)
![Screenshot 2024-07-18 151340](https://github.com/user-attachments/assets/27eb4d1c-0fcc-4414-a86b-71503e9c778b)
![Screenshot 2024-07-18 151329](https://github.com/user-attachments/assets/2006b9ff-ecfd-443c-927e-6d1d6855c31a)
![Screenshot 2024-07-18 151322](https://github.com/user-attachments/assets/f3864e94-7283-4cd4-8efc-891570f89984)
![Screenshot 2024-07-18 151315](https://github.com/user-attachments/assets/b16e1e19-372e-4555-958a-942a96a2b88c)
![Screenshot 2024-07-18 151309](https://github.com/user-attachments/assets/8dab171c-9fe6-4ad7-8be0-ea22b53c8f50)
![Screenshot 2024-07-18 151303](https://github.com/user-attachments/assets/563288a3-f8e5-4306-ad1b-d4b6e6172dcb)
![Screenshot 2024-07-18 151256](https://github.com/user-attachments/assets/522dbd58-4b6c-4a33-8cff-a5159de9dbcf)
![Screenshot 2024-07-18 151250](https://github.com/user-attachments/assets/8be5aa5e-5d6f-456c-b507-73f16bbb560c)
![Screenshot 2024-07-18 151242](https://github.com/user-attachments/assets/dbb6508f-1afc-428a-84df-4077ad73e5f9)
![Screenshot 2024-07-18 151234](https://github.com/user-attachments/assets/bd873c03-9b36-4cd1-849b-bea672a1f6e0)
![Screenshot 2024-07-18 151227](https://github.com/user-attachments/assets/ad737a7d-9a4b-45c6-a709-6279462d1ab9)
![Screenshot 2024-07-18 151220](https://github.com/user-attachments/assets/b8fe29f5-d47f-41c6-8eaa-2d85cdf65826)
![Screenshot 2024-07-18 151211](https://github.com/user-attachments/assets/4be2a2cc-5c35-45b6-be1c-42bf2ab7dacc)
![Screenshot 2024-07-18 151203](https://github.com/user-attachments/assets/108415cc-15f8-4853-a39c-829151ddf82a)
![Screenshot 2024-07-18 151154](https://github.com/user-attachments/assets/65189833-af86-4b04-be1b-a6a0b4524c19)

**Comment by tthuyhuong** [comment]
Trả về 6 cái
Get All có 6 cái
